---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tp2
  template:
    metadata:
      labels:
        app: tp2
    spec:
      containers:
      - name: tp2
        image: scarface54/tp2_cloud:v0
        ports:
        - containerPort: 5008