apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp2-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: tp2
  template:
    metadata:
      labels:
        app: tp2
    spec:
      containers:
      - name: tp2
        image: scarface54/flask-api:0.1
        ports:
        - containerPort: 52049
