# syntax=docker/dockerfile:1

FROM python:3.9-slim-buster

WORKDIR /home/luizademelo/tp2-cloud

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt


ENV DATASET_URL="https://raw.githubusercontent.com/luizademelo/TP2-CloudComputing/refs/heads/main/data/2023_spotify_ds1.csv"

COPY app/ .

CMD ["python3", "model.py"]
