# syntax=docker/dockerfile:1

FROM python:3.9-slim-buster

WORKDIR /home/luizademelo/tp2-cloud

# Install dependencies
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

# Copy the entire project
COPY app/ .

# Set Flask environment variables
# ENV FLASK_APP=app.app
# ENV FLASK_RUN_HOST=0.0.0.0
# ENV FLASK_RUN_PORT=52049

EXPOSE 52049


# Run the Flask app
CMD ["flask", "run", "--host", "0.0.0.0", "--port", "52049"]

