version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "52049:52049" # Expose port 8080 on the host for the API
    networks:
      - my_net

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      - my_net
    depends_on:
      - api

networks:
  my_net:
