apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp2
  template:
    metadata:
      labels:
        app: tp2
    spec:
      containers:
      - name: tp2
        image: scarface54/flask-api:0.1
        ports:
        - containerPort: 52049
        env:
        - name: DATASET_URL
          value: "https://raw.githubusercontent.com/luizademelo/TP2-CloudComputing/refs/heads/main/data/2023_spotify_ds1.csv"  # Replace with your actual dataset URL
        volumeMounts:
        - mountPath: /data  # Path inside the container where the data will be available
          name: ml-model-volume  # Name of the volume from the PVC
      volumes:
      - name: ml-model-volume  # Volume definition
        persistentVolumeClaim:
          claimName: project2-pvc-luizagomes  # Name of the PVC to bind to
