apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp2-deployment-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luizagomes-project  # Label used for identifying the application
  template:
    metadata:
      labels:
        app: luizagomes-project  # Label used for identifying the application
    spec:
      containers:
      - name: model
        image: scarface54/model:0.1  # Image to generate the model
        ports:
        - containerPort: 52049
        env:
        - name: DATASET_URL
          value: "https://raw.githubusercontent.com/luizademelo/TP2-CloudComputing/refs/heads/main/data/2023_spotify_ds1.csv"  # Dataset URL
        volumeMounts:
        - mountPath: /data  # Shared path where rules.pickle will be stored
          name: ml-model-volume  # Name of the volume from the PVC
      volumes:
      - name: ml-model-volume
        persistentVolumeClaim:
          claimName: project2-pvc-luizagomes  # PVC to bind to
