apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp2-deployment-flask-api
spec:
  replicas: 15
  selector:
    matchLabels:
      app: luizagomes-project  
  template:
    metadata:
      labels:
        app: luizagomes-project  
    spec:
      containers:
      - name: flask-api
        image: scarface54/flask-api:0.1
        ports:
        - containerPort: 52049
        env:
        - name: DATASET_URL
          value: "https://raw.githubusercontent.com/luizademelo/TP2-CloudComputing/refs/heads/main/data/2023_spotify_ds2.csv"
        volumeMounts:
        - mountPath: /data  
          name: ml-model-volume  
      volumes:
      - name: ml-model-volume
        persistentVolumeClaim:
          claimName: project2-pvc-luizagomes 
