apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc-luizagomes
  namespace: luizagomes
spec:
  storageClassName: default-storage-class-luizagomes
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      namespace: luizagomes
  volumeName: project2-pv2-luizagomes