apiVersion: v1
kind: Service
metadata:
  name: tp2-service
spec:
  selector:
    app: luizagomes-project  
  ports:
    - protocol: TCP
      port: 52049        # Porta dentro do cluster
      targetPort: 52049  # Porta dentro do container
      nodePort: 30049    # Porta para acessar externamente
  type: NodePort
