apiVersion: v1
kind: Service
metadata:
  name: tp2-service
spec:
  selector:
    app: luizagomes-project  # Updated to match the label from the deployment
  ports:
    - protocol: TCP
      port: 52049        # Port exposed inside the cluster
      targetPort: 52049  # Port inside the container
      nodePort: 30049    # Port on the nodes to access externally
  type: NodePort
